# Importing all the necessary libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('file1.csv')   # reading the csv file
df

,Date,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,AQI,AQI_Bucket,PM10_SubIndex,PM2.5_SubIndex,SO2_SubIndex,NOx_SubIndex,NH3_SubIndex,CO_SubIndex,O3_SubIndex
0,2015-01-01,Ahmedabad,56.092852,97.528507,0.92,18.22,17.15,16.5722,0.92,27.64,133.36,149.0,Moderate,97.0,93.333333,33.75,21.25,4.00,0.000000,148.529412
1,2015-01-02,Ahmedabad,56.092852,97.528507,0.97,15.69,16.46,16.5722,0.97,24.55,34.06,97.0,Satisfactory,97.0,93.333333,30.00,20.00,4.00,0.000000,34.000000
2,2015-01-03,Ahmedabad,56.092852,97.528507,17.40,19.30,29.70,16.5722,17.40,29.07,30.70,300.0,Poor,97.0,93.333333,36.25,36.25,4.00,300.000000,30.000000
3,2015-01-04,Ahmedabad,56.092852,97.528507,1.70,18.48,17.97,16.5722,1.70,18.59,36.08,97.0,Satisfactory,97.0,93.333333,22.50,21.25,4.00,50.000000,36.000000
4,2015-01-05,Ahmedabad,56.092852,97.528507,22.10,21.42,37.76,16.5722,22.10,39.33,39.31,329.0,Very Poor,97.0,93.333333,48.75,46.25,4.00,329.411765,39.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,2020-03-29,Visakhapatnam,22.170000,57.420000,7.03,22.72,17.81,5.5500,0.11,11.33,41.66,86.0,Satisfactory,57.0,36.666667,13.75,21.25,1.25,0.000000,41.000000
630,2020-03-30,Visakhapatnam,21.620000,65.480000,6.23,24.02,17.83,5.4000,0.11,10.42,59.94,69.0,Satisfactory,65.0,35.000000,12.50,21.25,1.25,0.000000,59.000000
631,2020-03-31,Visakhapatnam,18.770000,52.170000,6.65,25.22,18.82,5.6400,0.11,8.52,46.99,84.0,Satisfactory,52.0,30.000000,10.00,22.50,1.25,0.000000,46.000000
632,2020-04-01,Visakhapatnam,30.430000,76.290000,9.90,33.10,25.65,5.3500,0.11,7.39,23.15,64.0,Satisfactory,76.0,50.000000,8.75,31.25,1.25,0.000000,23.000000
633,2020-04-02,Visakhapatnam,23.810000,66.290000,13.42,32.49,28.43,6.1400,0.11,5.91,9.06,73.0,Satisfactory,66.0,38.333333,6.25,35.00,1.50,0.000000,9.000000

# Creating Model for predicting the Output

In [3]:
final_df= df[['AQI', 'AQI_Bucket']].copy()
final_df

       AQI    AQI_Bucket
0    149.0      Moderate
1     97.0  Satisfactory
2    300.0          Poor
3     97.0  Satisfactory
4    329.0     Very Poor
..     ...           ...
629   86.0  Satisfactory
630   69.0  Satisfactory
631   84.0  Satisfactory
632   64.0  Satisfactory
633   73.0  Satisfactory

[634 rows x 2 columns]

# Labelling the categories.

In [4]:
final_df['AQI_Bucket'] = final_df['AQI_Bucket'].map({'Good' :0, 'Satisfactory' :1, 'Moderate' :2, 'Poor' :3, 'Very Poor' :4, 'Severe' :5}).astype(int) #mapping numbers
final_df.head()

     AQI  AQI_Bucket
0  149.0           2
1   97.0           1
2  300.0           3
3   97.0           1
4  329.0           4

# Predicting the values of AQI_Bucket w.r.t values of AQI using SVM

In [5]:
X = final_df[['AQI']]
y = final_df[['AQI_Bucket']]

In [6]:
# division into training and test sets.
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0) 
#  test_size :Ratio by which we are splitting
#70% model used for training and rest 30% used for testing for predicting actual accuracy.
#  Random state used for keeking values constant means we dont want to change them.

In [7]:
from sklearn.model_selection import cross_val_score 
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [8]:
from sklearn.svm import SVC
s = SVC()

s.fit(X_train,y_train)
predicts = s.predict(X_test)

c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

# Taking AQI as input for finding the category

In [10]:
import math  
print("Enter the value of AQI:")
AQI = float(input("AQI : "))
output = s.predict([[AQI]])
print(output)
#0-->Good
#1-->Satisfactory
#2-->moderate
#3-->poor
#4-->Very poor
#5-->Severe

Enter the value of AQI:
AQI : 110
[2]

c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

# Printing other parameters

In [12]:
print("Classification report of Support Vector Machines Report:")
print("")

print(classification_report(y_test,predicts)) # shows classification metrics precision, recall and f1 score

Classification report of Support Vector Machines Report:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.91      1.00      0.95        67
           2       1.00      0.93      0.97        61
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        12
           5       1.00      1.00      1.00         5

    accuracy                           0.96       159
   macro avg       0.82      0.82      0.82       159
weighted avg       0.94      0.96      0.95       159

c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [13]:
# Accuracy is the correctly classified data instances over the total number of data instances.
# Cross validation is to evaluate our models
accuracy = cross_val_score(s ,X, y, cv=7) #splitting the data according to cv dividing it into training and testing
print("Cross validation test results of accuracy:")
print(accuracy)
print("")
# get mean of every field
print("Accuracy result of Support Vector Machines is:",accuracy.mean()*100)
print("")

cm1=confusion_matrix(y_test,predicts) #evaluating the performance of a classification model
print("Confusion Matrix result of Support Vector Machines is:\n",cm1)
print("")

Cross validation test results of accuracy:
[0.96703297 0.96703297 0.91208791 0.89010989 0.95555556 0.93333333
 0.92222222]

Accuracy result of Support Vector Machines is: 93.53392639106926

Confusion Matrix result of Support Vector Machines is:
 [[ 0  3  0  0  0  0]
 [ 0 67  0  0  0  0]
 [ 0  4 57  0  0  0]
 [ 0  0  0 11  0  0]
 [ 0  0  0  0 12  0]
 [ 0  0  0  0  0  5]]

c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)